### ISSUE TITLE
Feature: when running as root, show a visual indication

### ISSUE THREAD

**Issue by imsnif** [imsnif/diskonaut#14]
Running as root can be dangerous, since we have permission to delete a lot of things we might not want to. It would be nice if we had a visual indication in the title that we're "running as root'.

**Comment by c3st7n** [comment]
Raised PR for this: #57

**Comment by imsnif** [comment]
Merged, will be part of the next release. Thanks @c3st7n !

**Comment by imsnif** [comment]
Released in 0.6.0
