### ISSUE TITLE
Feature: only show "(x = Small files)" legend when there are small files on the screen

### ISSUE THREAD

**Issue by imsnif** [imsnif/diskonaut#15]
Otherwise it might be a little confusing...

**Comment by pjsier** [comment]
@imsnif I'm interested in taking this on. From a quick look I'm thinking about adding `hide_small_files_legend` bool field to `BottomLine` and setting it based on whether `unrenderable_tile_coordinates` on `Board` is `None` similar to how `hide_delete` is working. Then we could avoid subtracting the small files length from the output line if it isn't needed. Let me know if I'm missing anything, thanks!

**Comment by imsnif** [comment]
Cool - sounds like a good direction. There is an edge case described in more detail here: https://github.com/imsnif/diskonaut/issues/62, but that's probably out of scope for this issue.
