### ISSUE TITLE
Feature: add an "Are you sure you want to quit?" modal

### ISSUE THREAD

**Issue by imsnif** [imsnif/diskonaut#16]
Right now, when we press "Ctrl-C" or "q" to exit, the app exits immediately. It would be nice if we could add a modal that prompts the user in case they pressed this by mistake.

**Comment by mhdmhsni** [comment]
hi @imsnif would you mind if i work on this?

**Comment by imsnif** [comment]
Sure :) Feel free to reach out if you have questions or need anything.

**Comment by mhdmhsni** [comment]
thanks! :)
please feel free to correct me if I'm wrong. so far I've figured out that i should define a new file inside modals folder, something like confirm_box and i need a new UiMode variant let's call it Quit. i need a new handler function which will be used to handle KeyPress event while the modal has been rendered and the rendering logic if I'm right is something similar to showing a message to the user just before deleting a file or folder.

and...cool project! thumbs up. :)

**Comment by imsnif** [comment]
Sounds about right, good job!
The only hitch I can think of is that we might need need some sort of "mixed" UiState in case we're quitting while the app is still loading. Do you think you can find a solution for this? (let me know if you want help brainstorming)

**Comment by mhdmhsni** [comment]
well, so far, the core functionality of the confirm modal works fine (using both 'q' and 'Ctrl+c'), just needs some polishing and code cleaning.

![Peek 2020-06-21 20-47](https://user-images.githubusercontent.com/21965688/85229780-0f20db80-b401-11ea-9c58-c3b635e67bde.gif)

but about the hitch you mentioned, i need to dive deeper into the code.
I'll inform you in case of anything. thanks again.

**Comment by mhdmhsni** [comment]
Hi, about the "mixing" UiState issue, i found this solution:

i changed "Exiting(String)" UiMode variant to "Exiting { message, app_loaded }" where app_loaded contains a reference of latest value of the "app.loaded" variable.
This way, the Display module can decide what it has to render on ExitingMode. and also my "handle_keypress_exiting_mode" function can decide where to go back if user decides NOT to quit.

Please feel free to add any comment. :) I would appreciate your remarks and suggestions.

**Comment by imsnif** [comment]
That sounds like a great solution. We'll have to test it in various situations to make sure it's okay, but I can't think of anything you missed.

**Comment by imsnif** [comment]
Released
