### ISSUE TITLE
This is Awesome

### ISSUE THREAD

**Issue by zicklag** [imsnif/diskonaut#21]
Hey there, sorry to leave an issue just to say good job, but I figured it'd be worth it. :wink:

Anyway, this is the best disk usage analyzer I've ever seen. I've tried out a few different ones, GUI or TUI based, and maybe I haven't searched super hard, but this one beats all the ones I've tried for one big reason: It lets you look around *while the tool is working*.

That's amazing for UX, and the terminal UI is very nice. Good job on this, and good job with a simple, but nice README and some issues to start with for further improvements. :tada:

**Comment by imsnif** [comment]
Thank you for the kind words, @zicklag! I put a lot of thought into diskonaut's UX and am really happy you like it. :)

I'm going to close this issue though. I hope you don't mind. If you have any other input about the app, please feel free to open an issue.
