### ISSUE TITLE
Fix: Show quit shortcut ('q') in the legend

### ISSUE THREAD

**Issue by imsnif** [imsnif/diskonaut#33]
In order to quit the app, we use 'q' or 'ctrl-c'. It should also appear in the legend on the bottom line near the other controls.

**Comment by olehs0** [comment]
Hi @imsnif ! It's a really great project, thank you for it. About the issue, should it looks like something like this? 
![image](https://user-images.githubusercontent.com/45392385/85213163-548ecb80-b363-11ea-9ce1-4a01c3ffb455.png)

**Comment by imsnif** [comment]
Hey @olehs0, glad to see you here. :) I'm happy you like diskonaut.

Let's have just `<q> - quit` in the bottom line for now. It's getting a little big and I want to trim it down a little bit (especially once we implement this: https://github.com/imsnif/diskonaut/issues/36)
