### ISSUE TITLE
Feature: emacs keys

### ISSUE THREAD

**Issue by ebroto** [imsnif/diskonaut#36]
It would be nice if diskonaut supported emacs keys for navigation.

Those keys would be:
left  -> Ctrl + b
right -> Ctrl + f
up    -> Ctrl + p
down  -> Ctrl + n

I think it's not necessary to show that those are supported in the legend as they are kinda common in TUIs and assumed to "just work" because of being supported by GNU Readline.

**Comment by imsnif** [comment]
Thanks for pointing that out! As an eVIl user myself, I was actually not aware of them. Let's add them, definitely. I think part of this fix would be to change navigation part of the legend to this:

`< ← ↓ ↑ → > - move around`

Then have all arrows/vim/emacs/etc. keys work. What do you think?

**Comment by ebroto** [comment]
Works for me! :+1:
