### ISSUE TITLE
New feature: delete key to delete

### ISSUE THREAD

**Issue by rory** [imsnif/diskonaut#41]
Currently one presse `Control-D` to delete an entry. My first thought was to press the `Delete` key! I suggest making `Delete` also work to delete

**Comment by imsnif** [comment]
This makes a lot of sense to me. I also received some complaints about ctrl-d elsewhere. I mostly wanted to avoid the "cat walking in the keyboard" situation by requiring the extra ctrl, but I guess with the modal prompt one key is totally reasonable.

Thanks for pointing this out!

Let's change ctrl-d to the `Delete` key, and also change the controls line legend accordingly.

**Comment by maxheyer** [comment]
@imsnif I will give it a try

**Comment by imsnif** [comment]
Released in 0.6.0 - thanks @maxheyer !

**Comment by therealprof** [comment]
This broke deletion on macOS in iTerm2 for me. No idea how to emulate a "Delete" key, at the very least this should probably work with BACKSPACE or DELETE.

**Comment by maxheyer** [comment]
@imsnif I would also add the BACKSPACE key. Are you okay with that?

**Comment by imsnif** [comment]
Oi! That's not good :/ Sorry for that.

Umm... I don't know a lot about macs in this case, so maybe you can help me out, @therealprof ?
The mac keyboard does seem to have a delete key. So is it just not working in iterm, or not working in general? Or am I misunderstanding something?

As for backspace: I was told by other mac users that it's more of a "go back" sort of thing, so in diskonaut it is aliased to the same thing as ESC (going up a folder). I don't mind changing it to deleting, but I'd really like things to be as consistent as possible (if only in order to have a consistent controls legend).

And thanks, @maxheyer ! Let's figure out the best thing to do here and then I'd be happy if you want to implement it. :)

**Comment by maxheyer** [comment]
@imsnif I am also use macOS. Only iTerm does not know what to do when you send a DELETE event with <fn-backspace>.

**Comment by therealprof** [comment]
> Umm... I don't know a lot about macs in this case, so maybe you can help me out, @therealprof ?
> The mac keyboard does seem to have a delete key. So is it just not working in iterm, or not working in general? Or am I misunderstanding something?
> 
> As for backspace: I was told by other mac users that it's more of a "go back" sort of thing, so in diskonaut it is aliased to the same thing as ESC (going up a folder). I don't mind changing it to deleting, but I'd really like things to be as consistent as possible (if only in order to have a consistent controls legend).

All good questions. On my Macs (from different eras, the latest one a 2017" 15 MBP) the key is labelled via symbol pointing left and acting like a backspace key. There seem to be keyboards where this is labelled delete but still acting like a backspace key.

As of now the "backspace" key doesn't do anything at all in diskonaut.However I found out that with option and control as modifiers it acts as a "go up" function and with fn it acts as a delete and would delete a directory in diskonaut.

I've never considered the backspace key to be anything but a backspace key, i.e. to correct spelling errors. It also works as a delete key in system dialogs (I remembers after accidentally deleting all keyboard layouts while trying to figure out which keycode it produces 😅).

I guess I would generally prefer BACKSPACE and DELETE to remove directories, on my Linux laptop the DEL key is also rather inconvenient to reach and on many keyboards in custom spots whereas the backspace key sometimes varies in size but is always where you'd expect to find it.

To go up we still have ESC, no?

**Comment by maxheyer** [comment]
@imsnif To delete a file or directory in macOS' Finder, you can use < command + BACKSPACE >.

**Comment by therealprof** [comment]
> @imsnif To delete a file or directory in macOS' Finder, you can use < command + BACKSPACE >.

Yeah, but that's because any command is usually triggered with the "command" modifier.

**Comment by imsnif** [comment]
Hmm... alright. Thanks for the input @therealprof and @maxheyer.
Seems to me that the most straightforward way of making this one-key cross-platform would be to use BACKSPACE. Do you two agree?

**Comment by maxheyer** [comment]
> Do you two agree?
👍

**Comment by imsnif** [comment]
Awesome. @maxheyer, would you like to implement this?

**Comment by maxheyer** [comment]
@imsnif Tonight or tomorrow

**Comment by imsnif** [comment]
This was released in 0.8.0
