### ISSUE TITLE
Feature: Hide items from the view

### ISSUE THREAD

**Issue by therealprof** [imsnif/diskonaut#49]
It would be super to have a feature which would allow me to hide selected folders from the view. Especially with Rust projects there's usually a huge `target` directory completely swamping out everything else.

**Comment by imsnif** [comment]
I definitely agree this is an issue. I was planning on addressing this through: https://github.com/imsnif/diskonaut/issues/1
(see especially my edit there from now).

What do you think?

**Comment by therealprof** [comment]
#1 would potentially do the trick for me, but I have a feeling that is going to be quite a bit trickier to implement. 😅

**Comment by imsnif** [comment]
I understand what you're saying. :) For sure, such a full fledged feature with the UI indication, the controls legend and everything involved will be a bit much to implement.

How about if we start with a small chunk? Let's say have a hidden feature that if you press `+`, does not render the largest file, if you press `-`, it reverses this behaviour. Of course with the usual "don't do this if there's only one file" caveat. I think this will not be too hard to implement (certainly not harder than an ignore pattern), will provide the functionality you desire and will put us one step closer to the zoom in/out feature. What do you think?

**Comment by imsnif** [comment]
Hey @therealprof, I just released an implementation of #1 in version 0.7.0. I'm going to close this issue, please let me know if you feel this is not a good enough solution, and then I'll reopen this issue and we can discuss it.

**Comment by therealprof** [comment]
Works great, I love it! Thanks so much.
