### ISSUE TITLE
Option to delete without confiration?

### ISSUE THREAD

**Issue by rory** [imsnif/diskonaut#68]
If I want to delete a lot of files, and let's pretend I can be trusted, is there anyway to 'delete without confirmation? `ncdu` has this feature

**Comment by imsnif** [comment]
Sounds like a good feature. Let's implement it as a command line flag. Let me know if you'd like to work on this and I'll remove the Help Wanted tag.

**Comment by imsnif** [comment]
This has been implemented and merged into main. I hope to release a new version with it shortly. Thanks @markafarrell !
