### ISSUE TITLE
failure="0.1" not available, the current version is 0.1.8

### ISSUE THREAD

**Issue by yurivict** [imsnif/diskonaut#69]
Here https://github.com/imsnif/diskonaut/blob/main/Cargo.toml#L15

See the Rust's ```failure``` crate: https://crates.io/crates/failure

**Comment by imsnif** [comment]
Hey, I'm not sure I understand. Were you trying to build/run and failed, or?

**Comment by yurivict** [comment]
The build can't find failure="0.1" because https://crates.io/crates/failure doesn't have it any more.

**Comment by imsnif** [comment]
I think 0.1 should install anything that is semver compatible (eg. 0.1.8 too in this case). I'm not managing to reproduce this either, I'm afraid.
What I'm doing:
* cleaning the cache (in my case `rm -rf ~/.cargo/registry/cache/github.com-1ecc6299db9ec823/failure-0.1.8`)
* doing `cargo build`

I get:
````  
Downloaded failure v0.1.8
Downloaded 2 crates (42.5 KB) in 0.71s
Finished dev [unoptimized + debuginfo] target(s) in 0.74s
```

Could you share what you're doing exactly and what result you're getting? Maybe we can try to get to the bottom of this.

**Comment by yurivict** [comment]
You are right, this was some intermittent problem.

Thanks!
Yuri
