### ISSUE TITLE
The folder takes up too much space (7091231513.3G)

### ISSUE THREAD

**Issue by David-Valters** [imsnif/diskonaut#86]
The folder takes up too much space (7091231513.3G)
in fact, the folder takes up 659 KB
OS: Ubuntu 20.04.4 LTS on Windows 10 x86_64
 Shell: bash 5.0.17
![зображення](https://user-images.githubusercontent.com/46930139/161378652-57ed67ae-a66e-4b1a-92a6-ba50d950cc5f.png)
![зображення](https://user-images.githubusercontent.com/46930139/161378713-b39b5e66-d4bc-4251-a895-4b539ecb34b4.png)

**Comment by nova446** [comment]
is it showing the size of the folder as that when it is actually less than that

**Comment by David-Valters** [comment]
I deleted Windows, so unfortunately I can't reproduce the bug
