### ISSUE TITLE
Feature Request: Ability to not cross filesystem boundaries.

### ISSUE THREAD

**Issue by ForeverNooob** [imsnif/diskonaut#89]
Hi,

Currently (`v0.11.0`) when you have mounted (remote) filesystems, `diskonaut` is also accounting them in its scan.

I would love to see a flag like `-xdev` in the (GNU) `find` command or `-x` in the `ncdu` command which tells `diskonaut` to ignore all directories that are other filesystem mounts.

Thanks in advance for your consideration.

**Comment by vctls** [comment]
@ForeverNooob Isn't this the same as #23 ?

**Comment by ForeverNooob** [comment]
@vctls I have no idea how I missed that, sorry!
